#springboot的端口设置
server:
  port: 8080

#springboot整合druid数据库连接池的配置（包括配置时区
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/olpcs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath:mapper/*.xml

